### ISSUE TITLE
Right-mouse click support?

### ISSUE THREAD

**Issue by orschiro** [RyutaKojima/simpleGestures#1]
Dear @RyutaKojima,

I am very grateful for your work. Thank you!

By far the simplest implementation of gestures that I have found. 

The only problem I am facing concerns the right-mouse click context menu.

In some apps, such as Google Docs, the context menu offers essential functionality that I don't want to miss. 

Would it be possible to enable the context menu by holding down `Ctrl`?

Thankfully,

Robert

**Comment by RyutaKojima** [comment]
Thank you Robert.
I'm not good at English. Sorry.

Your request is, 
while you are holding down the control disable the extension?
is it right?

**Comment by orschiro** [comment]
Dear @RyutaKojima,

That's exactly what I would love to see in order to being able to access the context menu when I need it! 

Do you think this would be possible to implement?

Thankfully,

Robert

**Comment by RyutaKojima** [comment]
Dear Robert.

We have released version 0.0.6 to corresponding disabled gesture.
Please try it.

**Comment by orschiro** [comment]
Dear @RyutaKojima,

I updated to version 0.0.7. Outstanding release. Disabling the extension using `CTRL` works perfectly.

I am very grateful. ツ

Robert
