### ISSUE TITLE
New feature: Open the link in the background 

### ISSUE THREAD

**Issue by Moostek** [RyutaKojima/simpleGestures#75]
Hello, 

first of all, i really like your pure simple "simpleGestures" add-on, i was looking for it. Thank you for your job on this, really. Anyway, i have one tip, an **enhancement** for "simpleGestures". 

I really miss the option to open the link in the background: 
**"new tab(link open in the background)"**

I would like to to use "↓" gesture to open the link in the background (after the mother Tab). 

Do you think that you can add and implement this feature to the "simpleGestures"? 

Thank you!

**Comment by RyutaKojima** [comment]
Hello, @Moostek 

Thanks for the message and for using it.

> "new tab(link open in the background)"

I think this is a feature that a lot of people want, so I'll consider including it in the next update.
Please wait for a while until the implementation is complete.

Finally, thank you so much for your valuable input!

**Comment by RyutaKojima** [comment]
Version 1.3.1 has been released!

**Comment by Moostek** [comment]
It works perfect, thank you for your effort on this and the fast update!;)
