### ISSUE TITLE
Update "new tab(link open)": boost the pixel resolution for the initial drag move point (above link) 

### ISSUE THREAD

**Issue by Moostek** [RyutaKojima/simpleGestures#76]
Hello, i have one more thing to report. In many of my attempts to open the the link to the new tab via **"new tab(link open)"** with  **"↓"**  gesture there is just opened the new blank tab, but not the weblink itself. 

I have focused on this and i found why it happens. I am used from _Gesturefy_ from _Firefox_ that the initial touch of the mouse button (again, with the same "↓" gesture) could be laid and started simply above the link, and then i just go across the we blink and it is opened. Well, this is a good feature, really practical, because it is a good policy for the cases i miss the exact part of the web link on the initial drag move touch;) 

But with your add-on i have to focus right exactly on the web link (yes, in this case it works). But sometimes i miss the the web link (starting point of the drag move on it) and in this case the new blank tab is opened (instead of the web link in new tab). Well, it is pretty annoying;) So do you think that you can update this with the way described above and boost the pixel tolerance for the starting point of the initial drag move? 
That will be nice! 

Thanks!

**Comment by Moostek** [comment]
I have to confirm that on many web links the simpleGestures add-on does not work;( After go across web link, then it opens just blank New Tab, instead of the web link itself. I use (Chrome based) Brave Browser. The point that sometimes it works, sometimes not. It is not really clear to me now what is the cause of this malfunction. 

Will you examine this and fix this, please?

**Comment by RyutaKojima** [comment]
@Moostek 

Thank you for introducing us to a great feature.
Let me think about this for a moment.

We have also divided the bug reports into separate Issues. #80

**Comment by RyutaKojima** [comment]
@Moostek 

Thank you for your excellent report!
I have identified the cause and the fix is complete!

I hope to be able to release a new version 1.6.3 with the problem fixed soon.
